model: us.anthropic.claude-3-5-haiku-20241022-v1:0
api: bedrock
max_tokens: 4000
temperature: 0.0
concurrent_requests: 30
read_cost: 0.8
write_cost: 4
human_readable_id: Claude-3.5-Haiku (Bedrock)
date: "2024-10-22"
