model: us.anthropic.claude-sonnet-4-20250514-v1:0
api: bedrock
max_tokens: 64000
concurrent_requests: 2
temperature: 1
top_p: null
read_cost: 3
write_cost: 15
batch_processing: false
human_readable_id: Claude-Sonnet-4.0
date: "2025-05-26"