model: us.meta.llama4-scout-17b-instruct-v1:0
api: bedrock
max_tokens: 8192
temperature: 0.6
top_p: 0.9
read_cost: 0.22
write_cost: 0.88
human_readable_id: Llama-4-Scout
date: "2025-04-05"
concurrent_requests: 8
