model: us.amazon.nova-lite-v1:0
api: bedrock
max_tokens: 4000
temperature: 0.0
concurrent_requests: 20
read_cost: 0.06
write_cost: 0.24
human_readable_id: Amazon Nova Lite (Bedrock)
date: "2024-12-19"
