model: anthropic/claude-opus-4
api: openrouter
max_tokens: null
temperature: 0.6
top_p: null
# provider:
#   allow_fallbacks: False
#   order:
#   - amazon-bedrock
read_cost: 15
write_cost: 75
human_readable_id: Claude Opus 4 (Openrouter)
date: "2025-01-21"
reasoning:
  effort: "minimal"