model: x-ai/grok-3-mini
api: openrouter
max_tokens: 130000
read_cost: 0.3
write_cost: 0.5
human_readable_id: Grok 3 Mini (high)
concurrent_requests: 10
reasoning_effort: high
temperature: 0.3
date: "2025-04-09"